src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Typedejouet;

    /**
     * @ORM\Column(type="integer")
     */
    private $Trancheage;

    /**
     * @ORM\ManyToMany(targetEntity=Produit::class, mappedBy="categorie")
     */
    private $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypedejouet(): ?string
    {
        return $this->Typedejouet;
    }

    public function setTypedejouet(string $Typedejouet): self
    {
        $this->Typedejouet = $Typedejouet;

        return $this;
    }

    public function getTrancheage(): ?string
    {
        return $this->Trancheage;
    }

    public function setTrancheage(string $Trancheage): self
    {
        $this->Trancheage = $Trancheage;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->addCategorie($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            $produit->removeCategorie($this);
        }

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Marque;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Disponibilite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Photo;

    /**
     * @ORM\ManyToMany(targetEntity=Categorie::class, inversedBy="produits")
     */
    private $categorie;

    /**
     * @ORM\Column(type="text")
     */
    private $Descriptif;

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->Marque;
    }

    public function setMarque(string $Marque): self
    {
        $this->Marque = $Marque;

        return $this;
    }

    public function getDisponibilite(): ?bool
    {
        return $this->Disponibilite;
    }

    public function setDisponibilite(bool $Disponibilite): self
    {
        $this->Disponibilite = $Disponibilite;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }

    /**
     * @return Collection|categorie[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(categorie $categorie): self
    {
        $this->categorie->removeElement($categorie);

        return $this;
    }

    public function getDescriptif(): ?string
    {
        return $this->Descriptif;
    }

    public function setDescriptif(string $Descriptif): self
    {
        $this->Descriptif = $Descriptif;

        return $this;
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Repository\CategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ProduitRepository;
use Symfony\Component\HttpFoundation\Request;

class ProduitController extends AbstractController
{
    /**
     * @Route("/produit", name="produit")
     */

    public function produit(Request $request, ProduitRepository $repository, CategorieRepository $repositoryCategorie): Response
    {
        //var_dump($request->get('btn'));

        //var_dump($request->get('btnMarque'));

        if ($request->get('btn') != null) {
            $produits = $repository->createQueryBuilder('p')
                ->join('p.categorie', 'c')
                ->where('c.id = :category_id')
                ->setParameter('category_id', $request->get('btn'))
                ->getQuery()->getResult();
        } elseif ($request->get('btnMarque') != null) {
            $produits = $repository->findBy(['Marque' => $request->get('btnMarque')]);
        } else {
            $produits = $repository->findAll();
        }

        $marque = $repository->createQueryBuilder('p')
            ->select('p.Marque')
            ->groupBy('p.Marque')
            ->getQuery()->getResult();

        return $this->render('produit/produits.html.twig', [
            'produits' => $produits,
            'listCategory' => $repositoryCategorie->findAll(),
            'marque' => $marque,

        ]);
    }

    /**
     * @Route("/details-{id}", name="produitdetails")
     */

    public function details($id, ProduitRepository $repository): Response
    {
        return $this->render('produit/details.html.twig', [
            'details' => $repository->find($id),
        ]);
    }

    /**
     * @Route("/produit_bdd/{keyword}", name="produit_bdd")
     */

    public function produit_bdd($keyword)
    {
        $product = $this->getDoctrine()->getRepository(Produit::class)->createQueryBuilder('p')
            ->where('p.Nom LIKE :nom')
            ->setParameter("nom", "%" . $keyword . "%")
            ->getQuery()
            ->getResult();

        $newTab = [];

        foreach ($product as $row) {
            array_push($newTab, ["nom" => $row->getNom(), "id" => $row->getId()]);
        }
        echo json_encode($newTab);
        die();
    }
}

templates/produit/ajoutproduit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AjoutPanier!
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>

	<div class="example-wrapper">
		<h1>Page panier ✅</h1>

		<h2 class="title" ></h2>
		<h3>Descriptif</h3>
		<p class="desc" ></p>
		<img class="img" >


	</div>
{% endblock %}

templates/produit/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProduitController!
{% endblock %}

{% block body %}
	{#	<h1>Page details ✅</h1>
																	
																		<h2>{{details.nom}}</h2>
																		<img src="/uploads/{{details.photo}}">
																		<h3>Descriptif</h3>
																		<p>{{details.descriptif | raw}}</p>
																	</br>
																	<p>{{details.marque}}</p>
																	<button type="submit" data-name="{{details.nom}}" data-content="{{details.descriptif}}" data-img="{{details.photo}}" class="btn-ajouter">Ajouter au panier</button>
																	#}
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Fiche produits</title>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link
		href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
		<!-- CSS only -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

		<link rel="stylesheet" href="css/card.css">
		<link rel="stylesheet" href="css/style.css">
		<link rel="stylesheet" href="css/nav.css">
	</head>


	<section id="fiche_produit">
		<div class="container">
			<div
				class="row">
				<!--CAROUSSEL -->
				<article
					class="caroussel col-12 col-md-6">

					<!--IMAGE DU CAROUSSEL -->
					<img src="/uploads/{{details.photo}}" class="d-block img-fluid" alt="...">

				<!-- IMAGES DE LA GALLERIE -->
					{#<div class="row mt-3 d-none d-md-flex">
																<div class="col-4">
																	<img src="images/jouets/page_produit/xylophone_mini1.png" class="imgproduit img-fluid" alt="...">
																</div>
										
																<div class="col-4">
																	<img src="images/jouets/page_produit/xylophone_mini2.png" class="imgproduit img-fluid" alt="...">
																</div>
																<div class="col-4">
																	<img src="images/jouets/page_produit/xylophone_mini3.png" class="imgproduit img-fluid" alt="...">
																</div>
															</div>#}
				</article>

				<article class="col-12 col-md-6">
					<div class="artible-body">
						<h3>{{details.nom}}</h3>
						<div class="descriptif">
							<p>{{details.descriptif | raw}}</p>
						</div>

						<ul class="row">
							<li class="col-6 icon-wood">Bois</li>
							<li class="col-6 icon-glue">Colle écologique</li>
							<li class="col-6 icon-natural">Encre naturel</li>
							<li class="col-6 icon-eco">Plastique recyclé</li>
						</ul>


						<div
							class="row">
							<!--conteneur flex-->
							<div class="col-12 col-md-6 col-xl-6 ">
								<button type="submit" data-name="{{details.nom}}" data-content="{{details.descriptif}}" data-img="{{details.photo}}" class="btn-ajouter btn btn-primary">Ajouter a ma box</button>
							</div>
							<div id="dispo">
								<p>
									<img src="images/icon_dispo-jouets.png">Disponible</p>

							</div>
						</div>
					</div>
				</article>
			</div>
		</div>
	</section>
	<section id="avantages">
		<div class="container">
			<div
				class="row">
				<!--conteneur flex-->

				<div class="col-12 col-md-6 col-xl-3 text-center">
					<img src="images/avantages-bricetbroc/truck-delivery.png">
					<p>Livraison gratuite</p>
				</div>

				<div class="col-12 col-md-6 col-xl-3 text-center">
					<img src="images/avantages-bricetbroc/return-box.png">
					<p>Retour gratuit</p>
				</div>

				<div class="col-12 col-md-6 col-xl-3 text-center">
					<img src="images/avantages-bricetbroc/secure-payment_v2.png">
					<p>Paiement 100% sécurisé</p>
				</div>


				<div class="col-12 col-md-6 col-xl-3 text-center">
					<img src="images/avantages-bricetbroc/flexibility-box.png">
					<p>100% flexible</p>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

templates/produit/produits.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProduitController!
{% endblock %}

{% block body %}

	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Tous nos Jouets</title>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link
		href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
		<!-- CSS only -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<link rel="stylesheet" href="css/nav.css">
		<link rel="stylesheet" href="css/card.css">
		<link rel="stylesheet" href="css/style.css">
	</head>

	<body>

		<section id="tous-lesjouets">

			<div class="container">
				<div class="row">
					<div class="col text-center">
						<h2>Nos Jouets</h2>
						{#	<img class="form-geometric" src="images/geometrie/triangle93x101.png" alt="">#}
					</div>
					<div class="container">
						<div
							class="row">
							<!--conteneur flex-->
							<div class="col-4 col-md-6 col-xl-3 ">

								<div id="filtre">
									<h3 id="color">Ages</h3>


									<div id="choix">
										<input type="radio" id="age" name="age" value="age" checked>
										<label for="huey">0-12 mois (65)</label>
									</div>

									<div id="choix">
										<input type="radio" id="age" name="age" value="age">
										<label for="dewey">12-24 mois (65)</label>
									</div>

									<div id="choix">
										<input type="radio" id="age" name="age" value="age">
										<label for="louie">24-36 mois (65)</label>
									</div>

									<div id="choix">
										<input type="radio" id="age" name="age" value="age" checked>
										<label for="huey">3-5 ans (65)</label>
									</div>

									<div id="choix">
										<input type="radio" id="age" name="age" value="age" checked>
										<label for="huey">6-9 ans (65)</label>
									</div>

									<div id="choix">
										<input type="radio" id="age" name="age" value="age" checked>
										<label for="huey">10-12 ans (65)</label>
									</div>
									<!-- Boucle sur type de jouet -->
									<h3 class="titrefiltre">Types de jouets
									</h3>
									<form method="POST" action="/produit" id="formSearch">
										{% for category in listCategory %}
											<div>
												<input type="radio" class="formCategory" name="btn" value="{{category.id}}">
												<label for="category.id">
													{{category.typedejouet}}
												</label>
											</div>
										{% endfor %}

										<!-- Boucle sur Marque de jouet -->

										<h3 class="titrefiltre">Marque</h3>
										{% for marque in marque %}
											<div>
												<input type="radio" class="formMarque" name="btnMarque" value="{{marque.Marque}}">
												<label for="marque.id">
													{{marque.Marque}}
												</label>
											</div>
										{% endfor %}
									</form>

								</div>

							</div>

							<div class="col-8 col-md-6 col-xl-9">
								<div
									class="row">
									<!--section cards-->
									{% for produit in produits %}
										<div class="col-8 col-md-6 col-xl-4">
											<div class="card-product text-center">
												<div class="card-product-visuel">
													<a class="tag-new" href="#">new</a>
													<a class="bt-like" href="#"><img src="images/icons/icon_like-20x19.png" alt=""></a>
													<img src="/uploads/{{produit.photo}}" class="card-img-top">
												</div>
												<div class="card-product-body">
													<h3>{{produit.nom}}</h3>
													{#	<p>{{produit.descriptif | raw}}</p>#}
													<a href=" {{path('produitdetails', {'id':produit.id} )}}">Voir le details du produit</a>
												</br>
												<div class="btn btn-primary btn-ajouter" data-name="{{produit.nom}}" data-content="{{produit.descriptif}}" data-img="{{produit.photo}}">Ajouter au panier</div>
											</div>
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
			</body>
		</section>
	</body><!-- JavaScript Bundle with Popper --><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}
{% block javascripts %}
	<script src="./js/search.js"></script>
{% endblock %}